<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ $report->document_title }}</title>
  <style>
    body {
      font-family: DejaVu Sans, Arial, sans-serif;
      color: #2C2422;
      font-size: 12px;
      margin: 0;
    }

    h1 {
      margin: 0 0 8px;
      color: #852030;
      font-size: 20px;
    }

    h2 {
      margin: 18px 0 8px;
      color: #5C1220;
      font-size: 15px;
    }

    h3 {
      margin: 12px 0 6px;
      color: #5C1220;
      font-size: 13px;
    }

    p {
      margin: 0 0 4px;
    }

    .muted {
      color: #7A6A5A;
    }

    .meta-grid {
      margin-bottom: 10px;
      border: 1px solid #E0DBD5;
      padding: 10px;
    }

    .meta-grid p {
      margin-bottom: 2px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 8px;
    }

    th, td {
      border: 1px solid #E0DBD5;
      padding: 6px;
      vertical-align: top;
      text-align: left;
    }

    th {
      background: #F7ECEE;
      color: #5C1220;
    }

    .num {
      text-align: right;
    }

    .profit {
      color: #C49A6C;
      font-weight: 700;
    }

    .loss {
      color: #791F1F;
      font-weight: 700;
    }

    .section {
      margin-top: 12px;
    }
  </style>
</head>
<body>

<div class="pdf-footer">
  <span class="footer-left">Generated at: {{ now()->format('F j, Y') }}</span>
  <span class="footer-right">Page <span class="page-num"></span></span>
</div>
@php
  $range = $details['range'] ?? [];
  $salesTotals = $details['totals'] ?? [];
  $salesCounts = $details['counts'] ?? [];
  $salesEntries = $details['entries'] ?? [];
  $compensationTotals = $details['compensation_totals'] ?? [];
  $compensationCounts = $details['compensation_counts'] ?? [];
  $compensationEntries = $details['compensation_entries'] ?? [];
@endphp

<h1>{{ $report->document_title }}</h1>
<div class="meta-grid">
  <p><strong>Business:</strong> {{ $metadata['business_name'] ?? 'N/A' }}</p>
  <p><strong>Report Type:</strong> {{ ucfirst($reportType) }}</p>
  <p><strong>Version:</strong> {{ $report->version }}</p>
  <p><strong>Date Range:</strong>
    {{ isset($range['start_date']) ? \Carbon\Carbon::parse($range['start_date'])->format('F j, Y') : $report->start_date?->format('F j, Y') }}
    –
    {{ isset($range['end_date']) ? \Carbon\Carbon::parse($range['end_date'])->format('F j, Y') : $report->end_date?->format('F j, Y') }}
  </p>
  <p><strong>Generated At:</strong>
    {{ isset($metadata['generated_at']) ? \Carbon\Carbon::parse($metadata['generated_at'])->format('F j, Y, g:i A') : '' }}
  </p>
  <p><strong>Generated By:</strong> {{ $metadata['generated_by'] ?? 'N/A' }}
    ({{ $metadata['generated_by_username'] ?? 'N/A' }})</p>
  <p><strong>Stored File:</strong> {{ $metadata['stored_file_name'] ?? basename((string) $report->file_path) }}</p>
</div>

@if(in_array($reportType, ['sales', 'combined'], true))
  <div class="section">
    <h2>Sales Summary</h2>
    <table>
      <thead>
      <tr>
        <th>Business</th>
        <th class="num">Transactions</th>
        <th class="num">Amount</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>GCash</td>
        <td class="num">{{ $salesCounts['gcash_entries'] ?? 0 }}</td>
        <td class="num">{{ number_format((float) ($salesTotals['gcash_sales'] ?? 0), 2) }}</td>
      </tr>
      <tr>
        <td>Coffee</td>
        <td class="num">{{ $salesCounts['coffee_entries'] ?? 0 }}</td>
        <td class="num">{{ number_format((float) ($salesTotals['coffee_sales'] ?? 0), 2) }}</td>
      </tr>
      <tr>
        <td>Print</td>
        <td class="num">{{ $salesCounts['print_entries'] ?? 0 }}</td>
        <td class="num">{{ number_format((float) ($salesTotals['print_sales'] ?? 0), 2) }}</td>
      </tr>
      <tr>
        <td>Ethereal</td>
        <td class="num">{{ $salesCounts['ethereal_entries'] ?? 0 }}</td>
        <td class="num">{{ number_format((float) ($salesTotals['ethereal_sales'] ?? 0), 2) }}</td>
      </tr>
      <tr>
        <td><strong>Overall Sales</strong></td>
        <td class="num"><strong>{{ $salesCounts['all_entries'] ?? 0 }}</strong></td>
        <td class="num profit"><strong>{{ number_format((float) ($salesTotals['overall_sales'] ?? 0), 2) }}</strong>
        </td>
      </tr>
      </tbody>
    </table>
  </div>

  <div class="section">
    <h3>Sales Detail Entries</h3>
    @if(count($salesEntries) === 0)
      <p class="muted">No sales entries in the selected range.</p>
    @else
      <table>
        <thead>
        <tr>
          <th>#</th>
          <th>Module</th>
          <th>Item</th>
          <th>Sale Name</th>
          <th class="num">Original Price</th>
          <th class="num">Amount Charged</th>
          <th>Date</th>
          <th>Details</th>
        </tr>
        </thead>
        <tbody>
        @foreach($salesEntries as $index => $entry)
          @php
            $originalPrice = (float) ($entry['reference_item_original_price'] ?? 0);
            $amountCharged = (float) ($entry['amount'] ?? 0);
            $hasVariance = $originalPrice > 0 && $amountCharged !== $originalPrice;
          @endphp
          <tr>
            <td>{{ $index + 1 }}</td>
            <td>{{ $entry['module'] ?? '—' }}</td>
            <td>{{ $entry['reference_item_name'] ?? '—' }}</td>
            <td>{{ $entry['sale_name'] ?? '—' }}</td>
            <td class="num">
              {{ $originalPrice > 0 ? number_format($originalPrice, 2) : '—' }}
            </td>
            <td class="num {{ $hasVariance ? 'loss' : '' }}">
              {{ number_format($amountCharged, 2) }}
              @if($hasVariance)
                <div style="font-size:10px; font-weight:400;">
                  {{ $amountCharged < $originalPrice ? '▼' : '▲' }}
                  {{ number_format(abs($amountCharged - $originalPrice), 2) }}
                </div>
              @endif
            </td>
            <td>{{ isset($entry['sale_date']) && $entry['sale_date']
                ? \Carbon\Carbon::parse($entry['sale_date'])->format('M j, Y, g:i A')
                : '—' }}</td>
            <td>
              @forelse($entry['metadata'] ?? [] as $label => $value)
                @if($value !== null && $value !== '')
                  <div><span
                      class="muted">{{ ucwords(str_replace('_', ' ', (string) $label)) }}:</span> {{ is_numeric($value) ? number_format((float) $value, 2) : $value }}
                  </div>
                @endif
              @empty
                <span class="muted">—</span>
              @endforelse
            </td>
          </tr>
        @endforeach
        </tbody>
      </table>
    @endif
  </div>
@endif

@if(in_array($reportType, ['compensation', 'combined'], true))
  <div class="section">
    <h2>Compensation Summary</h2>
    <table>
      <thead>
      <tr>
        <th>Metric</th>
        <th class="num">Value</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>Total Runs</td>
        <td class="num">{{ $compensationCounts['runs_total'] ?? 0 }}</td>
      </tr>
      <tr>
        <td>Pending Runs</td>
        <td class="num">{{ $compensationCounts['runs_pending'] ?? 0 }}</td>
      </tr>
      <tr>
        <td>Finalized Runs</td>
        <td class="num">{{ $compensationCounts['runs_finalized'] ?? 0 }}</td>
      </tr>
      <tr>
        <td>Gross Pay</td>
        <td class="num">{{ number_format((float) ($compensationTotals['gross_pay'] ?? 0), 2) }}</td>
      </tr>
      <tr>
        <td>Total Deductions</td>
        <td class="num loss">{{ number_format((float) ($compensationTotals['total_deductions'] ?? 0), 2) }}</td>
      </tr>
      <tr>
        <td><strong>Net Pay</strong></td>
        <td class="num profit"><strong>{{ number_format((float) ($compensationTotals['net_pay'] ?? 0), 2) }}</strong>
        </td>
      </tr>
      </tbody>
    </table>
  </div>

  <div class="section">
    <h3>Compensation Detail Entries</h3>
    @if(count($compensationEntries) === 0)
      <p class="muted">No compensation runs in the selected range.</p>
    @else
      <table>
        <thead>
        <tr>
          <th>Run</th>
          <th>Status</th>
          <th>Period</th>
          <th class="num">Net Pay</th>
          <th>Details</th>
        </tr>
        </thead>
        <tbody>
        @foreach($compensationEntries as $entry)
          <tr>
            <td>{{ $entry['entry_name'] ?? '' }}</td>
            <td>{{ $entry['metadata']['payment_status'] ?? '' }}</td>
            <td>
              {{ isset($entry['metadata']['period_start']) ? \Carbon\Carbon::parse($entry['metadata']['period_start'])->format('M j, Y') : '—' }}
              –
              {{ isset($entry['metadata']['period_end']) ? \Carbon\Carbon::parse($entry['metadata']['period_end'])->format('M j, Y') : '—' }}
            </td>
            <td class="num">{{ number_format((float) ($entry['amount'] ?? 0), 2) }}</td>
            <td>
              <div><span
                  class="muted">Computation Mode:</span> {{ ucwords(str_replace('_', ' ', $entry['metadata']['computation_mode'] ?? '—')) }}
              </div>
              <div><span
                  class="muted">Gross Pay:</span> {{ number_format((float) ($entry['metadata']['gross_pay'] ?? 0), 2) }}
              </div>
              <div><span
                  class="muted">Total Deductions:</span> {{ number_format((float) ($entry['metadata']['total_deductions'] ?? 0), 2) }}
              </div>
              <div><span class="muted">No. of Employees:</span> {{ $entry['metadata']['employee_count'] ?? 0 }}</div>
            </td>
          </tr>
        @endforeach
        </tbody>
      </table>
    @endif
  </div>
@endif
{{-- Page number footer, rendered by dompdf on every page --}}
<style>
  /* push page content up to leave room for footer */
  @page { margin-bottom: 52px; }

  .pdf-footer {
    position: fixed;
    bottom: -36px;
    left: 0;
    right: 0;
    border-top: 1px solid #E0DBD5;
    padding-top: 5px;
    font-size: 9px;
    color: #7A6A5A;
  }
  .pdf-footer .footer-center { text-align: center; }
  .pdf-footer .footer-left   { position: absolute; left: 0; }
  .pdf-footer .footer-right  { position: absolute; right: 0; }
  .page-num:after  { content: counter(page); }
</style>
</body>
</html>
